# Generated by Django 4.2 on 2023-04-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='empdept',
            new_name='dept',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='designation',
        ),
    ]
