# Generated by Django 4.2 on 2023-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_empdept_employeedetail_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
