# Generated by Django 4.2 on 2023-06-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeedata_managerdetail_delete_employeedetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='manager',
        ),
    ]
