# Generated by Django 4.2 on 2023-04-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeedetail_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='dept',
            new_name='department',
        ),
    ]
