# Generated by Django 4.2 on 2023-04-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_dept_employeedetail_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='designation',
        ),
    ]
