# Generated by Django 4.2 on 2023-04-18 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_remove_employeedetail_designation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeDetail',
            new_name='ManagerDetail',
        ),
    ]
