# Generated by Django 4.2 on 2023-04-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='fullname',
            field=models.CharField(max_length=200),
        ),
    ]
