# Generated by Django 4.2 on 2023-06-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employeedata_manager'),
        ('employee', '0010_alter_employeedata_manager'),
    ]

    operations = [
    ]
